In [31]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
 
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/weather-training-data/Weather Training Data.csv


# import datbase

In [32]:
import sklearn
rain_df= pd.read_csv('/kaggle/input/weather-training-data/Weather Training Data.csv')
rain_df.drop(['row ID','Location'],inplace=True, axis=1)

rain_df


MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0         13.4     22.9       0.6          NaN       NaN           W   
1          7.4     25.1       0.0          NaN       NaN         WNW   
2         17.5     32.3       1.0          NaN       NaN           W   
3         14.6     29.7       0.2          NaN       NaN         WNW   
4          7.7     26.7       0.0          NaN       NaN           W   
...        ...      ...       ...          ...       ...         ...   
99511      8.0     20.7       0.0          NaN       NaN         ESE   
99512      3.5     21.8       0.0          NaN       NaN           E   
99513      2.8     23.4       0.0          NaN       NaN           E   
99514      3.6     25.3       0.0          NaN       NaN         NNW   
99515      5.4     26.9       0.0          NaN       NaN           N   

       WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity9am  \
0               44.0          W        WNW          20.0  ...         71.0   
1               44.0        NNW        WSW           4.0  ...         44.0   
2               41.0        ENE         NW           7.0  ...         82.0   
3               56.0          W          W          19.0  ...         55.0   
4               35.0        SSE          W           6.0  ...         48.0   
...              ...        ...        ...           ...  ...          ...   
99511           41.0         SE          E          19.0  ...         56.0   
99512           31.0        ESE          E          15.0  ...         59.0   
99513           31.0         SE        ENE          13.0  ...         51.0   
99514           22.0         SE          N          13.0  ...         56.0   
99515           37.0         SE        WNW           9.0  ...         53.0   

       Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0             22.0       1007.7       1007.1       8.0       NaN     16.9   
1             25.0       1010.6       1007.8       NaN       NaN     17.2   
2             33.0       1010.8       1006.0       7.0       8.0     17.8   
3             23.0       1009.2       1005.4       NaN       NaN     20.6   
4             19.0       1013.4       1010.1       NaN       NaN     16.3   
...            ...          ...          ...       ...       ...      ...   
99511         32.0       1028.1       1024.3       NaN       7.0     11.6   
99512         27.0       1024.7       1021.2       NaN       NaN      9.4   
99513         24.0       1024.6       1020.3       NaN       NaN     10.1   
99514         21.0       1023.5       1019.1       NaN       NaN     10.9   
99515         24.0       1021.0       1016.8       NaN       NaN     12.5   

       Temp3pm  RainToday RainTomorrow  
0         21.8         No            0  
1         24.3         No            0  
2         29.7         No            0  
3         28.9         No            0  
4         25.5         No            0  
...        ...        ...          ...  
99511     20.0         No            0  
99512     20.9         No            0  
99513     22.4         No            0  
99514     24.5         No            0  
99515     26.1         No            0  

[99516 rows x 21 columns]

# **Data Inspection**

In [33]:
print("Shape of the data frame: ",rain_df.shape)
print("Total null values: ",rain_df.isna().sum())
print("Duplicate values: ",rain_df.duplicated().sum())

Shape of the data frame:  (99516, 21)
Total null values:  MinTemp            443
MaxTemp            230
Rainfall           979
Evaporation      42531
Sunshine         47317
WindGustDir       6521
WindGustSpeed     6480
WindDir9am        7006
WindDir3pm        2648
WindSpeed9am       935
WindSpeed3pm      1835
Humidity9am       1233
Humidity3pm       2506
Pressure9am       9748
Pressure3pm       9736
Cloud9am         37572
Cloud3pm         40002
Temp9am            614
Temp3pm           1904
RainToday          979
RainTomorrow         0
dtype: int64
Duplicate values:  31


# **remove duplicates**

In [34]:
rain_df.drop_duplicates(inplace=True)
print("Shape of the data frame: ",rain_df.shape)
print("\n")
print("Species categories with its count \n",rain_df["RainTomorrow"].value_counts())
print("Duplicate values: ",rain_df.duplicated().sum())

Shape of the data frame:  (99485, 21)


Species categories with its count 
 RainTomorrow
0    77128
1    22357
Name: count, dtype: int64
Duplicate values:  0


In [35]:
rain_df.describe()

MinTemp       MaxTemp      Rainfall  Evaporation      Sunshine  \
count  99073.000000  99284.000000  98508.000000  56985.00000  52199.000000   
mean      12.176266     23.218445      2.353716      5.46132      7.615090   
std        6.390882      7.115127      8.489019      4.16249      3.783008   
min       -8.500000     -4.100000      0.000000      0.00000      0.000000   
25%        7.600000     17.900000      0.000000      2.60000      4.800000   
50%       12.000000     22.600000      0.000000      4.80000      8.400000   
75%       16.800000     28.200000      0.800000      7.40000     10.600000   
max       33.900000     48.100000    371.000000     86.20000     14.500000   

       WindGustSpeed  WindSpeed9am  WindSpeed3pm   Humidity9am   Humidity3pm  \
count   93036.000000  98581.000000  97681.000000  98283.000000  97010.000000   
mean       39.976966     14.004849     18.650464     68.866376     51.433296   
std        13.581524      8.902323      8.801827     19.074951     20.777616   
min         6.000000      0.000000      0.000000      0.000000      0.000000   
25%        31.000000      7.000000     13.000000     57.000000     37.000000   
50%        39.000000     13.000000     19.000000     70.000000     52.000000   
75%        48.000000     19.000000     24.000000     83.000000     65.000000   
max       135.000000    130.000000     87.000000    100.000000    100.000000   

        Pressure9am   Pressure3pm      Cloud9am      Cloud3pm       Temp9am  \
count  89768.000000  89780.000000  61944.000000  59514.000000  98902.000000   
mean    1017.684638   1015.286204      4.447985      4.519122     16.970041   
std        7.110166      7.045189      2.886580      2.716618      6.488961   
min      980.500000    978.200000      0.000000      0.000000     -7.000000   
25%     1013.000000   1010.500000      1.000000      2.000000     12.300000   
50%     1017.700000   1015.300000      5.000000      5.000000     16.700000   
75%     1022.400000   1020.000000      7.000000      7.000000     21.500000   
max     1041.000000   1039.600000      9.000000      9.000000     40.200000   

            Temp3pm  RainTomorrow  
count  97612.000000  99485.000000  
mean      21.681340      0.224727  
std        6.931681      0.417405  
min       -5.100000      0.000000  
25%       16.600000      0.000000  
50%       21.100000      0.000000  
75%       26.400000      0.000000  
max       46.700000      1.000000

# **Showing label values**

In [36]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
rain_df["RainTomorrow"]=label_encoder.fit_transform(rain_df["RainTomorrow"])
print("\n")
print(rain_df["RainTomorrow"].value_counts())



RainTomorrow
0    77128
1    22357
Name: count, dtype: int64


# Encode categorical variables

In [37]:
categorical_columns = ['WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday']
rain_df = pd.get_dummies(rain_df, columns=categorical_columns, drop_first=True)

# **spliting dataset into features and label**

In [38]:
X=rain_df.drop(["RainTomorrow"],axis=1)
Y=rain_df["RainTomorrow"]

# replace missing values with mean

In [39]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)




# spliting dataset into train data and test data 

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_imputed,Y,test_size=0.2,random_state=3)

# Using Logistic Regression

In [41]:
from sklearn.linear_model import LogisticRegression
logistic_reg=LogisticRegression()
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
logistic_reg.fit(X_train,Y_train)
predicted_result=logistic_reg.predict(X_test)
print("Accuracy Score: ",accuracy_score(Y_test, predicted_result))

print("Confusion Matrix:\n ",confusion_matrix(Y_test, predicted_result))

print("Classification Report:\n ",classification_report(Y_test, predicted_result))

Accuracy Score:  0.8383675931044882
Confusion Matrix:
  [[14575   815]
 [ 2401  2106]]
Classification Report:
                precision    recall  f1-score   support

           0       0.86      0.95      0.90     15390
           1       0.72      0.47      0.57      4507

    accuracy                           0.84     19897
   macro avg       0.79      0.71      0.73     19897
weighted avg       0.83      0.84      0.83     19897



/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Using KNN

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)  
knn_model.fit(X_train, Y_train)
knn_predicted_result = knn_model.predict(X_test)

print("KNN Accuracy Score: ", accuracy_score(Y_test, knn_predicted_result))
print("KNN Confusion Matrix:\n", confusion_matrix(Y_test, knn_predicted_result))
print("KNN Classification Report:\n", classification_report(Y_test, knn_predicted_result))

KNN Accuracy Score:  0.8317836859828115
KNN Confusion Matrix:
 [[14310  1080]
 [ 2267  2240]]
KNN Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.93      0.90     15390
           1       0.67      0.50      0.57      4507

    accuracy                           0.83     19897
   macro avg       0.77      0.71      0.73     19897
weighted avg       0.82      0.83      0.82     19897



# Using K-means

In [43]:
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=2, random_state=42)  
X_clusters = kmeans_model.fit_predict(X_imputed)


kmeans_labels = np.zeros_like(Y)
kmeans_labels[X_clusters == 1] = 1 

print("K-Means Accuracy Score: ", accuracy_score(Y, kmeans_labels))
print("K-Means Confusion Matrix:\n", confusion_matrix(Y, kmeans_labels))
print("K-Means Classification Report:\n", classification_report(Y, kmeans_labels))

/opt/conda/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


K-Means Accuracy Score:  0.4401568075589285
K-Means Confusion Matrix:
 [[40324 36804]
 [18892  3465]]
K-Means Classification Report:
               precision    recall  f1-score   support

           0       0.68      0.52      0.59     77128
           1       0.09      0.15      0.11     22357

    accuracy                           0.44     99485
   macro avg       0.38      0.34      0.35     99485
weighted avg       0.55      0.44      0.48     99485



# Using RandomForest

In [44]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)  # You can adjust hyperparameters as needed
random_forest.fit(X_train, Y_train)
rf_predicted_result = random_forest.predict(X_test)

print("Random Forest Accuracy Score: ", accuracy_score(Y_test, rf_predicted_result))
print("Random Forest Confusion Matrix:\n", confusion_matrix(Y_test, rf_predicted_result))
print("Random Forest Classification Report:\n", classification_report(Y_test, rf_predicted_result))

Random Forest Accuracy Score:  0.8525405840076393
Random Forest Confusion Matrix:
 [[14733   657]
 [ 2277  2230]]
Random Forest Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.96      0.91     15390
           1       0.77      0.49      0.60      4507

    accuracy                           0.85     19897
   macro avg       0.82      0.73      0.76     19897
weighted avg       0.84      0.85      0.84     19897



# Using Decision Tree

In [45]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)  # You can adjust hyperparameters as needed
decision_tree.fit(X_train, Y_train)
dt_predicted_result = decision_tree.predict(X_test)

print("Decision Tree Accuracy Score: ", accuracy_score(Y_test, dt_predicted_result))
print("Decision Tree Confusion Matrix:\n", confusion_matrix(Y_test, dt_predicted_result))
print("Decision Tree Classification Report:\n", classification_report(Y_test, dt_predicted_result))

Decision Tree Accuracy Score:  0.7861486656279841
Decision Tree Confusion Matrix:
 [[13278  2112]
 [ 2143  2364]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.86      0.86     15390
           1       0.53      0.52      0.53      4507

    accuracy                           0.79     19897
   macro avg       0.69      0.69      0.69     19897
weighted avg       0.79      0.79      0.79     19897



# Using Naive Bayes

In [46]:
from sklearn.naive_bayes import GaussianNB
naive_bayes = GaussianNB()
naive_bayes.fit(X_train, Y_train)
nb_predicted_result = naive_bayes.predict(X_test)

print("Naive Bayes Accuracy Score: ", accuracy_score(Y_test, nb_predicted_result))
print("Naive Bayes Confusion Matrix:\n", confusion_matrix(Y_test, nb_predicted_result))
print("Naive Bayes Classification Report:\n", classification_report(Y_test, nb_predicted_result))


Naive Bayes Accuracy Score:  0.7420716690958435
Naive Bayes Confusion Matrix:
 [[11928  3462]
 [ 1670  2837]]
Naive Bayes Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.78      0.82     15390
           1       0.45      0.63      0.53      4507

    accuracy                           0.74     19897
   macro avg       0.66      0.70      0.67     19897
weighted avg       0.78      0.74      0.76     19897

